create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list sysclk_IBUF]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/avr_fpga_0/U0/cpu/F_OPC[0]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[1]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[2]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[3]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[4]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[5]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[6]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[7]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[8]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[9]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[10]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[11]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[12]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[13]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[14]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[15]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[16]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[17]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[18]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[19]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[20]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[21]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[22]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[23]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[24]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[25]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[26]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[27]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[28]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[29]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[30]} {design_1_i/avr_fpga_0/U0/cpu/F_OPC[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/avr_fpga_0/U0/C_PC[0]} {design_1_i/avr_fpga_0/U0/C_PC[1]} {design_1_i/avr_fpga_0/U0/C_PC[2]} {design_1_i/avr_fpga_0/U0/C_PC[3]} {design_1_i/avr_fpga_0/U0/C_PC[4]} {design_1_i/avr_fpga_0/U0/C_PC[5]} {design_1_i/avr_fpga_0/U0/C_PC[6]} {design_1_i/avr_fpga_0/U0/C_PC[7]} {design_1_i/avr_fpga_0/U0/C_PC[8]} {design_1_i/avr_fpga_0/U0/C_PC[9]} {design_1_i/avr_fpga_0/U0/C_PC[10]} {design_1_i/avr_fpga_0/U0/C_PC[11]} {design_1_i/avr_fpga_0/U0/C_PC[12]} {design_1_i/avr_fpga_0/U0/C_PC[13]} {design_1_i/avr_fpga_0/U0/C_PC[14]} {design_1_i/avr_fpga_0/U0/C_PC[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/avr_fpga_0/U0/I_PC[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 3 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/avr_fpga_0/U0/Q_LEDS[0]} {design_1_i/avr_fpga_0/U0/Q_LEDS[1]} {design_1_i/avr_fpga_0/U0/Q_LEDS[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 7 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/avr_fpga_0/U0/Q_7_SEGMENT[0]} {design_1_i/avr_fpga_0/U0/Q_7_SEGMENT[1]} {design_1_i/avr_fpga_0/U0/Q_7_SEGMENT[2]} {design_1_i/avr_fpga_0/U0/Q_7_SEGMENT[3]} {design_1_i/avr_fpga_0/U0/Q_7_SEGMENT[4]} {design_1_i/avr_fpga_0/U0/Q_7_SEGMENT[5]} {design_1_i/avr_fpga_0/U0/Q_7_SEGMENT[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 16 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/avr_fpga_0/U0/cpu/opcf/L_NEXT_PC[0]} {design_1_i/avr_fpga_0/U0/cpu/opcf/L_NEXT_PC[1]} {design_1_i/avr_fpga_0/U0/cpu/opcf/L_NEXT_PC[2]} {design_1_i/avr_fpga_0/U0/cpu/opcf/L_NEXT_PC[3]} {design_1_i/avr_fpga_0/U0/cpu/opcf/L_NEXT_PC[4]} {design_1_i/avr_fpga_0/U0/cpu/opcf/L_NEXT_PC[5]} {design_1_i/avr_fpga_0/U0/cpu/opcf/L_NEXT_PC[6]} {design_1_i/avr_fpga_0/U0/cpu/opcf/L_NEXT_PC[7]} {design_1_i/avr_fpga_0/U0/cpu/opcf/L_NEXT_PC[8]} {design_1_i/avr_fpga_0/U0/cpu/opcf/L_NEXT_PC[9]} {design_1_i/avr_fpga_0/U0/cpu/opcf/L_NEXT_PC[10]} {design_1_i/avr_fpga_0/U0/cpu/opcf/L_NEXT_PC[11]} {design_1_i/avr_fpga_0/U0/cpu/opcf/L_NEXT_PC[12]} {design_1_i/avr_fpga_0/U0/cpu/opcf/L_NEXT_PC[13]} {design_1_i/avr_fpga_0/U0/cpu/opcf/L_NEXT_PC[14]} {design_1_i/avr_fpga_0/U0/cpu/opcf/L_NEXT_PC[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list design_1_i/avr_fpga_0/U0/cpu/opcf/I_CLR]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets sysclk_IBUF]
